spring:
    datasource:
        url: jdbc:sqlite:/data/sqlite/sample.db
        driver-class-name: org.sqlite.JDBC
        hikari:
            connection-init-sql: PRAGMA foreign_keys=ON

    jpa:
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        hibernate:
            ddl-auto: validate

    flyway:
        enabled: true
        locations:
            - classpath:db/migration/common
            - classpath:db/migration/sqlite
